# Generated by Django 4.2.2 on 2023-06-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_job_skills'),
        ('account', '0004_remove_userprofile_skills_delete_skill_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.ManyToManyField(to='job.skill'),
        ),
    ]
