# Generated by Django 4.2.2 on 2023-06-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_userprofile_skills_userprofile_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='skills',
        ),
    ]
